# Generated by Django 5.1.6 on 2025-02-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_friends_alter_user_name_group'),
        ('api', '0005_update_user_schema'),
    ]

    operations = [
    ]
